# Generated by Django 5.1.4 on 2025-01-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('rating', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
