# Generated by Django 5.1.4 on 2025-01-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='art_collection',
            new_name='artcollection',
        ),
    ]
